### ISSUE TITLE
⚠️[Crítico] Refactor: Implementar o método update na geração do hex

### ISSUE THREAD

**Issue by Everbero** [Nocs-lab/inbcm-backend#29]
https://github.com/Nocs-lab/inbcm-backend/blob/3adc301586669d3cfccc0d8a1c8e7065b09e46c8/service/DeclaracaoService.ts#L270

O método createHash() espera que seja passada alguma informação em update(), caso contrário é gerada uma hash baseada em uma string vazia.

**Comment by thfields** [comment]
refiz a branch com a nova versão da development e implementei a refatoração.

**Comment by Everbero** [comment]
Não consigo localizar o seu ajuste, por favor comente com o hash do commit.

**Comment by thfields** [comment]
foi esse commit "feat: add method createHash and update method updateDeclaracao" 6029880f1b7afe623b4a96f45465fc446a153b88 
na branch: us-29-refactor-Implementar-o-método-update-na-geração-do-hex

**Comment by Everbero** [comment]
O PR #40 foi recusado por tentar fazer um [merge diretamente no branch main](https://github.com/Nocs-lab/inbcm-backend/pull/40#issuecomment-2181211764)

**Comment by thfields** [comment]
agora vai kk criei um arquivo utils para gerar o hash, nele criei 2 métodos, um para gerar o hash da declaração usando o ano e o id do museu. o outro método é cria para os arquivos usando o nome e o caminho do arquivo, com isso consigo chamar nas outra partes do código e gerar hash diferentes entre arquivos e declarações e os arquivos retificados.

**Comment by thfields** [comment]
este foi o commit: 
feat: create hashUtils com métodos parar gerar o hash da declaração e do arquivo](https://github.com/Nocs-lab/inbcm-backend/commit/e7c30b46941c99514d1a1567f5edc6d7502c3f68)
e7c30b46941c99514d1a1567f5edc6d7502c3f68

**Comment by thfields** [comment]
fiz o pull na dev e apaguei a branch. criei uma nova a partir da dev atualizada e inseri as mudanças e comentei os métodos criados.

a nova branch: us-29-refactor-geração-do-hex

o commit: 78787d02c379e178c69ef974c70446e5cf509ef4
