### ISSUE TITLE
🪲[Moderado] Bug: Utilização de Math.random()

### ISSUE THREAD

**Issue by Everbero** [Nocs-lab/inbcm-backend#53]
Math.random() não deve ser utilizado para gerar identificadores.

https://github.com/Nocs-lab/inbcm-backend/blob/207915c53a355ce79372fca3aad22fffdde5e9fc/scripts/generateMockData.ts#L7

**Comment by vadolasi** [comment]
Esse metodo está apenas sendo utilizado apenas para gerar dados mockados para fins de teste. A coluna "codIbram" não é definida como identificador no schema.

**Comment by Everbero** [comment]
Não é correto utilizar Math.random() para gerar identificadores únicos, existe a possibilidade de gerar identificadores iguais em testes de carga.
